spring:
  application:
    name: cloud-storage-api

  datasource:
    hikari:
      maximum-pool-size: 20
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      max-file-size: 5MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html
    operations-sorter: method
    display-request-duration: true
    try-it-out-enabled: true
    filter: true
    with-credentials: true
    persist-authorization: true
  cache:
    disabled: false


minio:
  client:
    url: ${MINIO_URL}
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
  buckets:
    names:
      user: user-files
  root-folder:
    pattern:
      prefix: user-
      suffix: -files

url:
  endpoints:
    publics:
      - /api/auth/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /v3/api-docs/**
      - /api-docs/**
      - /swagger-resources/**
      - /webjars/**
    logout: /api/auth/sign-out

cors:
  allowed:
    origins:
      - http://localhost:8080
      - http://localhost
    methods:
      - GET
      - POST
      - DELETE
      - OPTIONS
      - PUT
    credentials: true

logging:
  level:
    root: INFO
    org.example.cloudstorageapi: DEBUG